version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: saltfish
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saltfish_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: